### ISSUE TITLE
Frage

### ISSUE THREAD

**Issue by GamerMJay2008** [FlxiBoy1313/LanguageSystem#1]
Hey, wie soll das gehen? Wie soll man als beispiel das eng wort Hello auf Hallo übersetzen?

Vllt kann man ja das so machen

Übersetzungen:

Hello: "Hallo"

**Comment by FlxiBoy1313** [comment]
Ich glaube, du verstehst den Sinn etwas nicht. Das Plugin kann aktuell nur den Leuten helfen, wo auch eigenes Plugins machen oder ein eigenen Server machen. Mit diesem System ist gemeint, das du den Server in mehreren Sprachen einfach verwalten kannst. z.B Das Sprachen System wie auf Rushnation.

**Comment by GamerMJay2008** [comment]
Oh okay...

**Comment by FlxiBoy1313** [comment]
Gibt es sonst noch etwas? Oder eine neue Plugin Idee?

**Comment by GamerMJay2008** [comment]
Nope

**Comment by FlxiBoy1313** [comment]
ok
