### ISSUE TITLE
Question 

### ISSUE THREAD

**Issue by kostamax27** [FlxiBoy1313/LanguageSystem#2]
How can I use translations in other plugins?

**Comment by kostamax27** [comment]
@FlxiBoy1313 do weight have Discord?
If yes then write it to me

**Comment by FlxiBoy1313** [comment]
> How can I use translations in other plugins?

If you mean this, then you have to do the same thing in both files, only with different message languages ​​e.g. English or German. Then you take the code from README.md and insert it. The same thing happens in both places. The language is recognized automatically and you get the correct message.

**Comment by kostamax27** [comment]
> > How can I use translations in other plugins?
> 
> If you mean this, then you have to do the same thing in both files, only with different message languages ​​e.g. English or German. Then you take the code from README.md and insert it. The same thing happens in both places. The language is recognized automatically and you get the correct message.

Wtf ? I didn't understand something, can you make an example plugin?

**Comment by FlxiBoy1313** [comment]
Counter question, do you speak German? Then I think I could explain it a little better?

**Comment by kostamax27** [comment]
> Counter question, do you speak German? Then I think I could explain it a little better?

No. I speak Russian
Вот как-то так

**Comment by kostamax27** [comment]
> Counter question, do you speak German? Then I think I could explain it a little better?

You can make an example plugin like PlayerJoinEvent

**Comment by FlxiBoy1313** [comment]
Okay, one moment I'm going to create a sample plugin

**Comment by kostamax27** [comment]
> Okay, one moment I'm going to create a sample plugin

Ok thanks a lot I will wait. Maybe then I will understand

**Comment by FlxiBoy1313** [comment]
![image](https://user-images.githubusercontent.com/65186341/132998001-005922ac-4aac-49a0-b946-750887c47c5e.png)

**Comment by FlxiBoy1313** [comment]
I hope that explains it.

**Comment by kostamax27** [comment]
> I hope that explains it.

Hmmm. Sec

**Comment by kostamax27** [comment]
> I hope that explains it.
![Screenshot_2021-09-12-21-07-47-083_com cxinventor file explorer](https://user-images.githubusercontent.com/69608272/132998104-63250f69-ba31-4b0a-ac42-feedcfe39e5e.jpg)
![Screenshot_2021-09-12-21-07-42-728_com cxinventor file explorer](https://user-images.githubusercontent.com/69608272/132998107-19c32d3a-baea-4345-b25b-d802aafddbbb.jpg)
![Uploading Screenshot_2021-09-12-21-07-39-218_com.cxinventor.file.explorer.jpg…]()

**Comment by kostamax27** [comment]
> I hope that explains it.

I don't have a folder there "lang"

**Comment by FlxiBoy1313** [comment]
then create a folder called lang and create your files there e.g. english.yml and russian.yml and add it there

**Comment by kostamax27** [comment]
> I hope that explains it.
I created a folder "lang" and added 2 language
- Русский.yml
- English.yml
What's next ?
You need to write a message there, right?

**Comment by kostamax27** [comment]
> then create a folder called lang and create your files there e.g. english.yml and russian.yml and add it there

![Screenshot_2021-09-12-21-19-16-716_com cxinventor file explorer](https://user-images.githubusercontent.com/69608272/132998445-e1fc8490-91c2-4971-8f88-af72e2b9351a.jpg)

**Comment by FlxiBoy1313** [comment]
yes,  and now with the other file with the other language and it should work

**Comment by kostamax27** [comment]
> yes, and now with the other file with the other language and it should work

ok I'll try see you soon

**Comment by FlxiBoy1313** [comment]
remember that you also have one with default-lang, where a file exists. Alternatively, you can change the language briefly with / lang. This shows all current ones.

**Comment by kostamax27** [comment]
> I hope that explains it.

Hmmmm. So ?
![Screenshot_2021-09-12-21-35-50-749_com rhmsoft edit pro](https://user-images.githubusercontent.com/69608272/132998932-f6008df5-57c7-41d0-a888-9ac2551d5fa5.jpg)

**Comment by FlxiBoy1313** [comment]
what does Language:: stand for?

**Comment by FlxiBoy1313** [comment]
In addition, you forgot a **ge** when importing

**Comment by kostamax27** [comment]
> In addition, you forgot a **ge** when importing

Ouch. I didn't even notice now

**Comment by kostamax27** [comment]
> In addition, you forgot a **ge** when importing

so it was with you 
![Screenshot_2021-09-12-21-41-06-373_com opera gx](https://user-images.githubusercontent.com/69608272/132999054-b18b4919-f6dc-4037-b1b3-a3296d9ab7d5.jpg)

**Comment by kostamax27** [comment]
> > In addition, you forgot a **ge** when importing
> 
> so it was with you
> ![Screenshot_2021-09-12-21-41-06-373_com opera gx](https://user-images.githubusercontent.com/69608272/132999054-b18b4919-f6dc-4037-b1b3-a3296d9ab7d5.jpg)

Idk kind of right?
![Screenshot_2021-09-12-21-43-23-328_com rhmsoft edit pro](https://user-images.githubusercontent.com/69608272/132999128-cfd62cce-25fb-4b84-aa2d-e84ca226f76c.jpg)

**Comment by FlxiBoy1313** [comment]
Scroll over or go down a line, unfortunately I don't see it

**Comment by kostamax27** [comment]
> Scroll over or go down a line, unfortunately I don't see it

![Screenshot_2021-09-12-21-46-17-520_com rhmsoft edit pro](https://user-images.githubusercontent.com/69608272/132999196-fcee66af-f456-4c4d-9059-8702577d1cb6.jpg)

**Comment by FlxiBoy1313** [comment]
Okay, that's right.

**Comment by kostamax27** [comment]
> Okay, that's right.

ok i check

**Comment by kostamax27** [comment]
> Okay, that's right.

And you need to add
`$player->sendMessgae(Language::get($player, "join-message"))` ??

**Comment by FlxiBoy1313** [comment]
What?

**Comment by kostamax27** [comment]
> What?

Do I need to add this?
$player->sendMessgae(Language::get($player, "join-message"))

**Comment by kostamax27** [comment]
![Screenshot_2021-09-12-21-54-53-560_com rhmsoft edit pro](https://user-images.githubusercontent.com/69608272/132999448-10de6a17-a2e5-4ed6-98f9-5de8cb02b032.jpg)

**Comment by FlxiBoy1313** [comment]
When joining? If yes, no. the setJoinMessage already exists

**Comment by kostamax27** [comment]
> When joining? If yes, no. the setJoinMessage already exists

Hmmmm just for some reason does not write a message at the entrance

**Comment by FlxiBoy1313** [comment]
you also have to register the event when starting the plugin. that's missing

**Comment by kostamax27** [comment]
> When joining? If yes, no. the setJoinMessage already exists

![Screenshot_2021-09-12-21-57-07-110_com cxinventor file explorer](https://user-images.githubusercontent.com/69608272/132999491-b6157cc5-b5ca-415a-b99e-f766ce86bc8a.jpg)

**Comment by kostamax27** [comment]
> you also have to register the event when starting the plugin. that's missing

what event?

**Comment by FlxiBoy1313** [comment]
add this in onEnable() 
```php
$this->getServer()->getPluginManager()->registerEvents($this, $this);
```

**Comment by kostamax27** [comment]
> add this in onEnable()
> 
> ```
> $this->getServer()->getPluginManager()->registerEvents($this, $this);
> ```

Hmmm sec

**Comment by kostamax27** [comment]
> add this in onEnable()
> 
> ```
> $this->getServer()->getPluginManager()->registerEvents($this, $this);
> ```

Doesn't work all the same

**Comment by kostamax27** [comment]
> add this in onEnable()
> 
> ```
> $this->getServer()->getPluginManager()->registerEvents($this, $this);
> ```

Hmmm, Error

![Screenshot_2021-09-12-22-03-38-398_io scer pocketmine](https://user-images.githubusercontent.com/69608272/132999659-2eef7808-a67a-4462-8538-d678598d83b0.jpg)

**Comment by FlxiBoy1313** [comment]
```php
use pocketmine\event\**player**\PlayerJoinEvent;
```
:)

**Comment by kostamax27** [comment]
> ```
> use pocketmine\event\player\PlayerJoinEvent;
> ```
> 
> :)

Omg. OMG Works yes

**Comment by kostamax27** [comment]
> ```
> use pocketmine\event\player\PlayerJoinEvent;
> ```
> 
> :)

I'm testing. And by the way, it works for Form ?

**Comment by FlxiBoy1313** [comment]
If you do it this way, it works everywhere

**Comment by kostamax27** [comment]
> If you do it this way, it works everywhere

Ok thanks you

**Comment by FlxiBoy1313** [comment]
no problem. :)

**Comment by FlxiBoy1313** [comment]
Open on a new one or reopen this should be something else

**Comment by kostamax27** [comment]
> Open on a new one or reopen this should be something else

Hi @FlxiBoy1313. How to fix error ?

![Screenshot_2021-09-12-22-41-01-236_io scer pocketmine](https://user-images.githubusercontent.com/69608272/133000589-44fed77f-cdc7-4655-adaa-089f7f137932.jpg)

Line 64: $form->addButton(Language::get($player, "button-rules"));

**Comment by FlxiBoy1313** [comment]
If this has to work, the player has to be online. Therefore you have to check whether this player exists or add a player to the function if you do not have a player yet.

**Comment by kostamax27** [comment]
> If this has to work, the player has to be online. Therefore you have to check whether this player exists or add a player to the function if you do not have a player yet.

Hmmm ok

**Comment by kostamax27** [comment]
> If this has to work, the player has to be online. Therefore you have to check whether this player exists or add a player to the function if you do not have a player yet.

Like so ?

![Screenshot_2021-09-12-22-50-41-583_com cxinventor file explorer](https://user-images.githubusercontent.com/69608272/133000830-914f4097-6750-4e08-97b2-887e17060c30.jpg)

**Comment by FlxiBoy1313** [comment]
Jo, but you can also just try. I am happy to help with mistakes. :)

**Comment by kostamax27** [comment]
> Jo, but you can also just try. I am happy to help with mistakes. :)

Nothing changed :(

**Comment by FlxiBoy1313** [comment]
how do you mean?

**Comment by kostamax27** [comment]
> how do you mean?

![Screenshot_2021-09-12-22-56-34-515_io scer pocketmine](https://user-images.githubusercontent.com/69608272/133001022-40a5030c-e3bd-463f-978e-8f2590da91f9.jpg)

**Comment by FlxiBoy1313** [comment]
send your function

**Comment by kostamax27** [comment]
> send your function

![Screenshot_2021-09-12-23-00-09-383_com rhmsoft edit pro](https://user-images.githubusercontent.com/69608272/133001114-fb8a9d16-01cf-4397-9863-f1f33c1f2a03.jpg)
![Screenshot_2021-09-12-23-00-13-786_com rhmsoft edit pro](https://user-images.githubusercontent.com/69608272/133001116-3d74808f-8484-4541-904f-b3c7cf54a314.jpg)

**Comment by kostamax27** [comment]
> send your function

There may be a mistake?

```$form = $this->getServer()->getPluginManager()->getPlugin("FormAPI")->createSimpleForm(function (Player $player, int $data = null)```

**Comment by FlxiBoy1313** [comment]
Please send a line about it

**Comment by kostamax27** [comment]
> Please send a line about it

What ?

**Comment by FlxiBoy1313** [comment]
sind this:
```php
public function ...
```

**Comment by kostamax27** [comment]
> sind this:
> 
> ```
> public function ...
> ```

![Screenshot_2021-09-12-23-03-50-301_com rhmsoft edit pro](https://user-images.githubusercontent.com/69608272/133001187-27b87357-bbf6-42dc-a0fa-aaaaf4a88b57.jpg)

**Comment by FlxiBoy1313** [comment]
Okay, turn on Player $ sender, so 
```php
Player $sender
```

**Comment by FlxiBoy1313** [comment]
with the use
```php
use pocketmine\Player;
```

**Comment by FlxiBoy1313** [comment]
> > send your function
> 
> ![Screenshot_2021-09-12-23-00-09-383_com rhmsoft edit pro](https://user-images.githubusercontent.com/69608272/133001114-fb8a9d16-01cf-4397-9863-f1f33c1f2a03.jpg)
> ![Screenshot_2021-09-12-23-00-13-786_com rhmsoft edit pro](https://user-images.githubusercontent.com/69608272/133001116-3d74808f-8484-4541-904f-b3c7cf54a314.jpg)

You also have to add to jojoe777 Form API like this:
```php
use jojoe77777\FormAPI\CustomForm;
use jojoe77777\FormAPI\SimpleForm;
```

**Comment by kostamax27** [comment]
> Okay, turn on Player $sender, so
> 
> ```
> Player $sender
> ```

What ?

**Comment by FlxiBoy1313** [comment]
so
```php
public function ProfileUI(Player $sender) {
```

**Comment by kostamax27** [comment]
> so
> 
> ```
> public function ProfileUI(Player $sender) {
> ```

Ok sec

**Comment by kostamax27** [comment]
> so
> 
> ```
> public function ProfileUI(Player $sender) {
> ```



> so
> 
> ```
> public function ProfileUI(Player $sender) {
> ```
Error
Line 90: $form->sendToPlayer($sender);

**Comment by FlxiBoy1313** [comment]
> > > send your function
> > 
> > 
> > ![Screenshot_2021-09-12-23-00-09-383_com rhmsoft edit pro](https://user-images.githubusercontent.com/69608272/133001114-fb8a9d16-01cf-4397-9863-f1f33c1f2a03.jpg)
> > ![Screenshot_2021-09-12-23-00-13-786_com rhmsoft edit pro](https://user-images.githubusercontent.com/69608272/133001116-3d74808f-8484-4541-904f-b3c7cf54a314.jpg)
> 
> You also have to add to jojoe777 Form API like this:
> 
> ```
> use jojoe77777\FormAPI\CustomForm;
> use jojoe77777\FormAPI\SimpleForm;
> ```

.

**Comment by kostamax27** [comment]
> > > > send your function
> > > 
> > > 
> > > ![Screenshot_2021-09-12-23-00-09-383_com rhmsoft edit pro](https://user-images.githubusercontent.com/69608272/133001114-fb8a9d16-01cf-4397-9863-f1f33c1f2a03.jpg)
> > > ![Screenshot_2021-09-12-23-00-13-786_com rhmsoft edit pro](https://user-images.githubusercontent.com/69608272/133001116-3d74808f-8484-4541-904f-b3c7cf54a314.jpg)
> > 
> > 
> > You also have to add to jojoe777 Form API like this:
> > ```
> > use jojoe77777\FormAPI\CustomForm;
> > use jojoe77777\FormAPI\SimpleForm;
> > ```
> 
> .

![Screenshot_2021-09-12-23-18-50-206_com rhmsoft edit pro](https://user-images.githubusercontent.com/69608272/133001615-b63d7c29-a40c-46c0-8453-8d481e1dce3d.jpg)

**Comment by FlxiBoy1313** [comment]
Okay, so send me the complete function: 
```php
public function ProfileUI(Sender $sender) {
    //
}
```

**Comment by kostamax27** [comment]
> Okay, so send me the complete function:
> 
> ```
> public function ProfileUI(Sender $sender) {
>     //everything that is inside
> }
> ```

public function ProfileUI(Player $sender){ 
    	$form = $this->getServer()->getPluginManager()->getPlugin("FormAPI")->createSimpleForm(function (Player $player, int $data = null){
            $result = $data;
            if($result === null){
                return true;
            }             
            switch($result){
                case 0:
                $this->Peraturan($sender);
                $volume = mt_rand();
                $sender->getLevel()->broadcastLevelEvent($sender, LevelEventPacket::EVENT_SOUND_DOOR_BUMP, (int) $volume);
                break;
                }

**Comment by kostamax27** [comment]
> > Okay, so send me the complete function:
> > ```
> > public function ProfileUI(Sender $sender) {
> >     //everything that is inside
> > }
> > ```
> 
> public function ProfileUI(Player $sender){
> $form = $this->getServer()->getPluginManager()->getPlugin("FormAPI")->createSimpleForm(function (Player $player, int $data = null){
> $result = $data;
> if($result === null){
> return true;
> }

**Comment by kostamax27** [comment]
> > > Okay, so send me the complete function:
> > > ```
> > > public function ProfileUI(Sender $sender) {
> > >     //everything that is inside
> > > }
> > > ```
> > 
> > 
> > public function ProfileUI(Player $sender){
> > $form = $this->getServer()->getPluginManager()->getPlugin("FormAPI")->createSimpleForm(function (Player $sender, int $data = null){
> > $result = $data;
> > if($result === null){
> > return true;
> > }

Hmmm I don't know how to fix the error :(

**Comment by FlxiBoy1313** [comment]
send your whole file

**Comment by kostamax27** [comment]
> send your whole file

I was able to fix the error but now a new error
Line 42: $form = $this->getServer()->getPluginManager()->getPlugin("FormAPI")->createSimpleForm(function (Player $sender, int $data = null){

**Comment by FlxiBoy1313** [comment]
send the message from the console

**Comment by kostamax27** [comment]
> send the message from the console

New error :( 

Line 66:
![Screenshot_2021-09-12-23-38-42-229_io scer pocketmine](https://user-images.githubusercontent.com/69608272/133002097-20802d03-5c10-4d31-a3b0-5c132011d58e.jpg)

**Comment by FlxiBoy1313** [comment]
send code

**Comment by kostamax27** [comment]
> send code

![Screenshot_2021-09-12-23-40-46-597_com rhmsoft edit pro](https://user-images.githubusercontent.com/69608272/133002146-05ea4b17-2e8d-4162-8f61-1eda6ead1a1c.jpg)

**Comment by FlxiBoy1313** [comment]
replace $player to $sender

**Comment by kostamax27** [comment]
> replace $player to $sender

get($sender ?

**Comment by FlxiBoy1313** [comment]
yes

**Comment by kostamax27** [comment]
> yes

Hurray is working thanks you

**Comment by FlxiBoy1313** [comment]
no problem

**Comment by kostamax27** [comment]
> no problem

Okey see you later. Bye

**Comment by FlxiBoy1313** [comment]
Chiao
