### ISSUE TITLE
New Error ❌

### ISSUE THREAD

**Issue by kostamax27** [FlxiBoy1313/LanguageSystem#4]
![Screenshot_2021-09-13-00-32-30-311_com mojang minecraftpe](https://user-images.githubusercontent.com/69608272/133003459-b6b9b9ab-709b-47f6-97b2-866afabc9559.jpg)

Variables stopped working.
How to fix?

**Comment by FlxiBoy1313** [comment]
This is not yet supported. Currently only normal news goes, but with an update it will come soon.

**Comment by kostamax27** [comment]
> This is not yet supported. Currently only normal news goes, but with an update it will come soon.

Ok I will wait :)
